{{/* SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved. */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "nemoclaw-gpu.namespace" . }}
  labels:
    {{- include "nemoclaw-gpu.labels" . | nindent 4 }}
{{- end }}
